Resources:
  SesS3Rule:
    Type: AWS::SES::ReceiptRule
    Properties:
      Rule:
        Enabled: true
        Actions:
          - S3Action:
              BucketName: !Ref EmailsBucket
              ObjectKeyPrefix: emails
          - LambdaAction:
              FunctionArn: !GetAtt SesForwarderLambdaFunction.Arn
      RuleSetName: ${self:custom.environment.ses.ruleSetName}

Outputs:
  SesRule:
    Value:
      Ref: SesS3Rule
